/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-error-container": "#93000a",
        "surface-tint": "#124af0",
        "surface": "#fbf8ff",
        "tertiary-fixed-dim": "#ffb59b",
        "on-tertiary-fixed": "#380d00",
        "tertiary-container": "#c24100",
        "tertiary-fixed": "#ffdbcf",
        "on-surface-variant": "#434656",
        "on-secondary-fixed": "#081b38",
        "inverse-on-surface": "#f0effd",
        "secondary-fixed": "#d7e2ff",
        "on-secondary": "#ffffff",
        "on-tertiary-fixed-variant": "#812800",
        "surface-container-high": "#e7e7f4",
        "secondary-container": "#c6d7fd",
        "on-tertiary": "#ffffff",
        "surface-container-low": "#f3f2ff",
        "tertiary": "#993100",
        "surface-bright": "#fbf8ff",
        "on-surface": "#191b24",
        "on-secondary-container": "#4d5d7e",
        "primary-fixed": "#dde1ff",
        "on-error": "#ffffff",
        "surface-container-highest": "#e2e1ef",
        "on-primary-fixed-variant": "#0035be",
        "surface-variant": "#e2e1ef",
        "primary-container": "#2e5bff",
        "secondary-fixed-dim": "#b6c7ec",
        "primary-fixed-dim": "#b8c3ff",
        "on-primary-fixed": "#001356",
        "on-primary-container": "#efefff",
        "outline": "#747688",
        "error-container": "#ffdad6",
        "surface-dim": "#d9d9e6",
        "on-secondary-fixed-variant": "#364766",
        "secondary": "#4e5f7f",
        "on-background": "#191b24",
        "on-primary": "#ffffff",
        "error": "#ba1a1a",
        "surface-container-lowest": "#ffffff",
        "on-tertiary-container": "#ffece6",
        "surface-container": "#ededfa",
        "background": "#fbf8ff",
        "outline-variant": "#c4c5d9",
        "inverse-surface": "#2e303a",
        "inverse-primary": "#b8c3ff",
        "primary": "#0040e0",
        "success": "#137333",
        "success-bg": "#e6f4ea",
        "danger": "#c5221f",
        "danger-bg": "#fce8e6",
        "info": "#1967d2",
        "info-bg": "#e8f0fe",
        "warning": "#b06000",
        "warning-bg": "#fef7e0",
        "special": "#7b1fa2",
        "special-bg": "#f3e8fd"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "sidebar-width": "260px",
        "stack-sm": "8px",
        "stack-md": "12px",
        "gutter": "16px",
        "container-padding": "24px",
        "row-height-std": "44px",
        "stack-lg": "24px"
      },
      fontFamily: {
        "body-lg": ["IBM Plex Sans", "sans-serif"],
        "body-md": ["IBM Plex Sans", "sans-serif"],
        "label-md": ["IBM Plex Sans", "sans-serif"],
        "body-sm": ["IBM Plex Sans", "sans-serif"],
        "h1": ["IBM Plex Sans", "sans-serif"],
        "mono-label": ["IBM Plex Mono", "monospace"],
        "h3": ["IBM Plex Sans", "sans-serif"],
        "mono-id": ["IBM Plex Mono", "monospace"],
        "label-sm": ["IBM Plex Sans", "sans-serif"],
        "h2": ["IBM Plex Sans", "sans-serif"]
      },
      fontSize: {
        "body-lg": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "body-md": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "label-md": ["14px", { lineHeight: "20px", fontWeight: "500" }],
        "body-sm": ["13px", { lineHeight: "18px", fontWeight: "400" }],
        "h1": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "mono-label": ["11px", { lineHeight: "14px", letterSpacing: "0.02em", fontWeight: "500" }],
        "h3": ["16px", { lineHeight: "24px", fontWeight: "600" }],
        "mono-id": ["13px", { lineHeight: "18px", letterSpacing: "-0.01em", fontWeight: "400" }],
        "label-sm": ["12px", { lineHeight: "16px", fontWeight: "600" }],
        "h2": ["20px", { lineHeight: "28px", fontWeight: "600" }]
      }
    },
  },
  plugins: [],
}